server:
  port: 8081
  session:
    timeout: 10000
spring:
  profiles:
    active: @profileActive@
  application:
    name: api-person
  session:
    store-type: redis
  mvc:
    view:
      prefix: /
      suffix: .html
  rabbitmq:
    host: 39.107.239.107
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
  redis:
    host: 39.107.239.107
    port: 6379
    password: 7416kobe
eureka:
  client:
    serviceUrl:
      defaultZone: http://39.107.239.107:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
